all: createDir readDir removeDir createFile readFile removeFile createSymLink readSymLink readFileFromLink removeSymLink createHardLink removeHardLink readFilePermissions changeFilePermission

createDir:
	gcc createDir-a.c -o ../functions/createDir

readDir:
	gcc readDir-b.c -o ../functions/readDir

removeDir:
	gcc removeDir-c.c -o ../functions/removeDir

createFile:
	gcc createFile-d.c -o ../functions/createFile

readFile:
	gcc readFile-e.c -o ../functions/readFile

removeFile:
	gcc removeFile-f.c -o ../functions/removeFile

createSymLink:
	gcc createSymLink-g.c -o ../functions/createSymLink

readSymLink:
	gcc readSymLink-h.c -o ../functions/readSymLink

readFileFromLink:
	gcc readFileFromLink-i.c -o ../functions/readFileFromLink

removeSymLink:
	gcc removeSymLink-j.c -o ../functions/removeSymLink

createHardLink:
	gcc createHardLink-k.c -o ../functions/createHardLink

removeHardLink:
	gcc removeHardLink-l.c -o ../functions/removeHardLink

readFilePermissions:
	gcc readFilePermissions-m.c -o ../functions/readFilePermissions

changeFilePermission:
	gcc changeFilePermissions-n.c -o ../functions/changeFilePermission